security:
  encoders:
    Geo\UserBundle\Entity\User:
      algorithm: bcrypt
      cost: 12

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    #ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    administrators:
        entity: { class: GeoUserBundle:User, property: username }

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt|configurator|error)|css|images|js)/
      security: false

    static:
      pattern:   ^/(tos|help)$
      anonymous: ~

    nonesecure:
      pattern:   ^/(login|register)$
      anonymous: ~

    main:
      pattern: ^/
      form_login: ~
      logout: ~

  access_control:
    - { path: ^/(tos|help)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(login|register)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/cron, role: IS_AUTHENTICATED_ANONYMOUSLY } #remote cron
    - { path: ^/, role: ROLE_USER }
