parameters:
  project:
    name: "Refenes"
    version: 0.1

services:
  twig.extension.globals_extension:
    class: Geo\AppBundle\Twig\GlobalsExtension
    arguments:
      - @service_container
    tags:
      - { name: twig.extension }
  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }
