Geo\AppBundle\Entity\Transaction:
  type: entity
  table: transactions
  
  id:
    id:
      type: integer
      nullable: false
      id: true
      generator:
        strategy: IDENTITY
        
  fields:
    amount:
      type: decimal
      nullable: false
      precision: 10
      scale: 4
    comment:
      type: text
      nullable: true
      length: 65535

  manyToOne:
    person:
      targetEntity: Person
      joinColumn:
        name: person_id
        referencedColumnName: id

  oneToMany:
    shares:
      targetEntity: Share
      mappedBy: transaction
