Geo\UserBundle\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [username]
        message: "This username is already been used"
  properties:
    username:
      - Length:
          min: 6
          minMessage: "Your username must be at least {{ limit }} characters long"
    password:
      - Length:
          min: 6
          minMessage: "Your password must be at least {{ limit }} characters long"
  getters:
    passwordLegal:
      - "True": { message: "The password cannot match your username" }

Geo\UserBundle\Model\Changepass:
  properties:
    oldpassword:
      - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
          message: "Wrong value for your current password"
    newpassword:
      - Length:
          min: 6
          minMessage: "Your password must be at least {{ limit }} characters long"
